name: Deploy-NuSight

on:
  push:
    branches: [ 'master' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301    
    - name: Install dependencies
      working-directory: .
      run: dotnet restore
    - name: Build
      working-directory: .
      run: dotnet build --configuration Release --no-restore
    - name: Build Nuget
      working-directory: .
      run: dotnet pack -o ./output -c Release /p:Version=1.0.${{github.run_number}}
    - name: Push Nuget
      working-directory: .
      run: dotnet nuget push ./output/Md-Gist.1.0.${{github.run_number}}.nupkg -k ${{secrets.NUGET_API}} -s https://api.nuget.org/v3/index.json
